import { Locale } from "./en";

const ar: Locale = {
  // General
  welcome: "مرحبا",
  cart: "عربة التسوق",
  viewCart: "عرض العربة",
  total: "الإجمالي",
  elements: "عناصر",
  currentLang: "ع",
  currentLanguage: "عربي",
  offers: "عروض",
  doctorPrefix: "د.",

  // Accessibility
  menu: "القائمة",
  toggleTheme: "تبديل المظهر",
  switchLanguage: "تبديل اللغة",
  shareProduct: "مشاركة المنتج",
  openCart: "فتح العربة",
  firstPage: "الصفحة الأولى",
  previousPage: "الصفحة السابقة",
  nextPage: "الصفحة التالية",
  lastPage: "الصفحة الأخيرة",
  goToPage: "الانتقال إلى الصفحة",
  removeFromFavorites: "إزالة من المفضلة",
  addToFavorites: "إضافة إلى المفضلة",
  linkCopied: "تم نسخ الرابط إلى الحافظة",
  shareText: "تحقق من هذا!",
  sharedSuccessfully: "تم المشاركة بنجاح",
  shareFailed: "فشل المشاركة",
  copyFailed: "فشل النسخ إلى الحافظة",
  shareOnFacebook: "المشاركة على فيسبوك",
  shareOnTwitter: "المشاركة على تويتر",
  copyLink: "مشاركة / نسخ الرابط",

  // Navigation
  home: "الرئيسية",
  about: "عن المنصة",
  contactUs: "اتصل بنا",
  products: "المنتجات",
  categories: "الفئات",
  brands: "العلامات التجارية",

  // Search
  allCategories: "جميع الفئات",
  searchForProducts: "البحث عن المنتجات...",
  noResultsFound: "لا توجد نتائج",
  refundAmount: "مبلغ الاسترداد",

  // Account
  account: "الحساب",
  signin: "تسجيل الدخول",
  signup: "إنشاء حساب",
  signOut: "تسجيل الخروج",
  notification: "الإشعار",
  personalInfo: "المعلومات الشخصية",
  addresses: "العناوين",
  returns: "المرتجعات",
  wallet: "المحفظة",
  compareProducts: "مقارنة المنتجات",
  favorites: "المفضلة",
  orders: "الطلبات",
  notifications: "الإشعارات",
  reports: "التقارير",
  logout: "تسجيل الخروج",

  // Profile
  firstName: "الاسم الأول",
  lastName: "الاسم الأخير",
  phone: "رقم الهاتف",
  email: "البريد الإلكتروني",
  age: "العمر",
  gender: "النوع",
  address: "العنوان",
  specialization: "التخصص المهني",
  licenseNumber: "رقم الترخيص",
  bio: "السيرة المهنية",
  certificate: "ملف الشهادة",
  promoCode: "رمز ترويجي",
  accountDetails: "تفاصيل الحساب",
  selectSpecialization: "اختر التخصص",
  professionalInfo: "المعلومات المهنية",
  save: "حفظ",
  saveChanges: "حفظ التغييرات",
  cancel: "إلغاء",

  // Orders
  orderNumber: "رقم الطلب",
  orderStatus: "حالة الطلب",
  orderDate: "تاريخ الطلب",
  orderTotal: "إجمالي الطلب",
  viewDetails: "عرض التفاصيل",
  requestReturn: "طلب إرجاع",

  // Products
  productName: "اسم المنتج",
  quantity: "الكمية",
  buyNow: "اشتر الآن",
  description: "الوصف",
  reviews: "التقييمات",
  specifications: "المواصفات",

  // Cart & Checkout
  cartEmpty: "عربة التسوق فارغة",
  continueShopping: "متابعة التسوق",
  shipping: "الشحن",
  tax: "الضريبة",
  discount: "الخصم",
  login: "تسجيل الدخول",
  loginToViewCart: "لعرض عربة التسوق",
  pharmacies: "الصيدليات",
  youHaveOrdersWith: "لديك طلبات مع",

  // Payment
  paymentMethod: "طريقة الدفع",
  card: "بطاقة",
  cashOnDelivery: "الدفع عند الاستلام",
  payLater: "ادفع لاحقًا",

  // Auth
  signInTitle: "تسجيل الدخول",
  signInDescription: "سجل الدخول إلى حسابك",
  signUpTitle: "إنشاء حساب",
  signUpDescription: "قم بإنشاء حسابك، أدخل معلوماتك أدناه.",
  selectUserType: "اختر نوع المستخدم",
  user: "مستخدم",
  doctor: "طبيب",
  dontHaveAccount: "ليس لديك حساب؟",
  alreadyHaveAccount: "لديك حساب بالفعل؟",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  invalidEmailOrPassword: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  male: "ذكر",
  female: "أنثى",
  register: "تسجيل",
  confirmLogout: "تأكيد تسجيل الخروج",
  confirmLogoutMessage: "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  yesLogout: "نعم، تسجيل الخروج",
  lightMode: "الوضع الفاتح",
  darkMode: "الوضع الداكن",
  myOrders: "طلباتي",
  myChats: "المحادثات",
  myDose: "جرعتي",

  // Forms
  submit: "إرسال",
  clear: "مسح",
  search: "بحث",
  filter: "تصفية",
  reset: "إعادة تعيين",

  // Validation Errors
  firstNameRequired: "الاسم الأول مطلوب",
  lastNameRequired: "الاسم الأخير مطلوب",
  addressRequired: "العنوان مطلوب",
  genderMustBeMaleOrFemale: "يجب أن يكون النوع 'ذكر' أو 'أنثى'",
  ageRequired: "يجب أن يكون العمر رقمًا صحيحًا",
  phoneNumberMin: "يجب أن يكون رقم الهاتف 5 أحرف على الأقل",
  phoneNumberMax: "يجب ألا يتجاوز رقم الهاتف 20 حرفًا",
  invalidPhoneNumber:
    "رقم هاتف غير صالح. يُسمح فقط بالأرقام و +، -، _، ()، المسافات و .",
  phoneNumberMustHaveDigit: "يجب أن يحتوي رقم الهاتف على رقم واحد على الأقل",
  emailRequired: "يجب أن يكون البريد الإلكتروني صالحًا",
  passwordMin: "يجب أن تكون كلمة المرور 8 أحرف على الأقل",
  passwordConfirmationMin: "يجب أن يكون تأكيد كلمة المرور 8 أحرف على الأقل",
  passwordsMustMatch: "كلمات المرور يجب أن تتطابق",
  licenseNumberRequired: "رقم الترخيص مطلوب",
  specializationRequired: "التخصص مطلوب",
  certificateFileInvalid:
    "يجب أن يكون ملف الشهادة ملف PDF أو DOC أو DOCX أو JPG أو PNG أو JPEG أو SVG صالح",
  invalidCurrencyFormat: "تنسيق العملة غير صالح",
  productIdRequired: "معرف المنتج مطلوب",
  productNameRequired: "اسم المنتج مطلوب",
  productSlugRequired: "رابط المنتج مطلوب",
  quantityMin: "يجب أن تكون الكمية 1 على الأقل",
  imageMustBeUrl: "يجب أن تكون الصورة رابط URL صالح",
  cartMinItems: "يجب أن تحتوي العربة على عنصر واحد على الأقل",
  totalItemsMin: "يجب أن يكون إجمالي العناصر 1 على الأقل",
  discountMin: "يجب أن يكون الخصم 0 على الأقل",
  sessionCartIdRequired: "معرف جلسة العربة مطلوب",
  nameRequired: "الاسم مطلوب",
  cardNumberInvalid: "يجب أن يكون رقم البطاقة 16 رقمًا",
  expiryInvalid: "يجب أن تكون مدة الصلاحية بتنسيق MM/YY",
  cvvInvalid: "CVV غير صالح",
  firstNameMin: "يجب أن يكون الاسم الأول حرفين على الأقل",
  ageMin: "يجب أن يكون العمر رقمًا صحيحًا",
  profileImageUrl: "يجب أن تكون صورة الملف الشخصي رابط URL صالح",
  addressNameRequired: "اسم العنوان مطلوب",
  buildingRequired: "المبنى مطلوب",
  areaRequired: "المنطقة مطلوبة",
  cityRequired: "المدينة مطلوبة",
  planIdRequired: "معرف الخطة مطلوب",
  pharmacyNameArRequired: "اسم المتجر بالعربية مطلوب",
  pharmacyNameEnRequired: "اسم المتجر بالإنجليزية مطلوب",
  pharmacyAddressArRequired: "عنوان المتجر بالعربية مطلوب",
  pharmacyAddressEnRequired: "عنوان المتجر بالإنجليزية مطلوب",
  pharmacyEmailInvalid: "يجب أن يكون بريد المتجر الإلكتروني صالحًا",
  paymentMethodInvalid: "يجب أن تكون طريقة الدفع 'بطاقة' أو 'نقدًا' أو 'محفظة'",
  currentPasswordRequired: "كلمة المرور الحالية مطلوبة",
  newPasswordMin: "يجب أن تكون كلمة المرور الجديدة 8 أحرف على الأقل",
  newPasswordConfirmationMin:
    "يجب أن يكون تأكيد كلمة المرور الجديدة 8 أحرف على الأقل",
  newPasswordsMustMatch: "كلمات المرور الجديدة يجب أن تتطابق",
  messageRequired: "الرسالة مطلوبة",

  // Messages
  success: "نجح",
  error: "خطأ",
  loading: "جاري التحميل...",
  noData: "لا توجد بيانات متاحة",
  confirmDelete: "هل أنت متأكد أنك تريد الحذف؟",

  // Common Actions
  edit: "تعديل",
  view: "عرض",
  download: "تحميل",
  upload: "رفع",
  close: "إغلاق",
  previous: "السابق",

  // Reports
  comments: "التعليقات",
  reviewsReport: "تقرير المراجعات",
  commentsReport: "تقرير التعليقات",
  promocodes: "أكواد الترويج",

  // Misc
  showMore: "عرض المزيد",
  showLess: "عرض أقل",
  browseAll: "تصفح الكل",
  uniqueProducts: "منتجات فريدة",
  topRatedProducts: "المنتجات الأعلى تقييمًا",
  topSellingProducts: "المنتجات الأكثر مبيعًا",
  top: "الأعلى",
  ratedBrands: "علامات تجارية مقيمة",
  categoriesSubheading:
    "اختر من مجموعة واسعة من الأدوية والمنتجات الصحية ومنتجات العناية الشخصية - كل ما تحتاجه في مكان واحد.",
  brandsSubheading:
    "اختر من مجموعة واسعة من الأدوية والمنتجات الصحية ومنتجات العناية الشخصية - كل ما تحتاجه في مكان واحد.",
  viewAll: "عرض الكل",
  availableInStock: "متوفر في المخزون",
  notAvailable: "غير متوفر",
  buyNowButton: "اشتري الآن",
  details: "التفاصيل",
  compare: "مقارنة",
  support: "الدعم",
  quickLink: "رابط سريع",
  downloadApp: "تحميل التطبيق",
  allRightsReserved: "جميع الحقوق محفوظة",
  signInRegister: "تسجيل الدخول / التسجيل",
  wishlist: "قائمة الرغبات",
  privacyPolicy: "سياسة الخصوصية",
  termsOfService: "شروط الاستخدام",
  faq: "الأسئلة الشائعة",
  addToCompare: "أضف للمقارنة",
  productDetails: "تفاصيل المنتج",
  genericName: "الاسم العلمي",
  category: "الفئة",
  brand: "العلامة التجارية",
  productType: "النوع",
  form: "الشكل",
  strength: "القوة",
  productionDate: "تاريخ الإنتاج",
  packSize: "حجم العبوة",
  rateProduct: "تقييم المنتج",
  productNotFound: "المنتج غير موجود",
  productNotFoundDescription:
    "المنتج المطلوب غير متوفر حالياً. تصفح مجموعتنا الواسعة من الأدوية والمنتجات الصحية.",
  similarProducts: "المنتجات المشابهة",
  price: "السعر",
  status: "الحالة",
  inStock: "متوفر في المخزون",
  outOfStock: "غير متوفر",
  addToCart: "أضف إلى العربة",
  itemAddedToCart: "تمت إضافة المنتج إلى العربة بنجاح",
  itemUpdatedInCart: "تمت تحديث المنتج في العربة بنجاح",
  notEnoughStock: "المخزون غير كافٍ",
  notSignedIn: "أنت لست مسجلاً الدخول!",
  goToSignIn: "اذهب لتسجيل الدخول",
  doctors: "الأطباء",
  customers: "العملاء",
  doctorComments: "تعليقات الأطباء",
  customerComments: "تعليقات المستخدمين",
  noCustomerComments: "لا توجد تعليقات من المستخدمين بعد.",
  noDoctorComments: "لا توجد تعليقات من الأطباء بعد.",
  productReviews: "تقييمات ومراجعات المنتج",
  showAll: "عرض الكل",
  shoppingCart: "سلة التسوق",
  manageCartAcrossStores: "إدارة سلة التسوق الخاصة بك عبر المتاجر المختلفة",
  pharmacy: "صيدلية",
  productsCount: "عدد المنتجات",
  totalAmount: "الإجمالي",
  pricePerUnit: "السعر للوحدة",
  orderSummary: "ملخص الطلب",
  subtotal: "المجموع الفرعي",
  estimatedTax: "الضريبة المقدرة",
  walletBalance: "رصيد المحفظة",
  checkout: "إتمام الشراء",
  noAddressesAvailable: "لا توجد عناوين متاحة",
  addNewAddress: "إضافة عنوان جديد",
  name: "الاسم",
  phoneNumber: "رقم الهاتف",
  building: "المبنى",
  city: "المدينة",
  area: "المنطقة",
  unitPrice: "سعر الوحدة",
  makeDefaultAddress: "اجعل العنوان افتراضي",
  addressSavedSuccessfully: "تم حفظ العنوان بنجاح",
  failedToSaveAddress: "فشل في حفظ العنوان",
  addressDeletedSuccessfully: "تم حذف العنوان بنجاح",
  defaultAddress: "العنوان الافتراضي",
  deleteAddress: "حذف العنوان",
  deleteAddressConfirmation: "هل أنت متأكد أنك تريد حذف هذا العنوان؟",
  delete: "حذف",
  chooseLocation: "اختر الموقع",
  default: "افتراضي",
  next: "التالي",
  savedCards: "البطاقات المحفوظة",
  expired: "منتهية الصلاحية",
  transferPaymentToNumber: "يرجى تحويل الدفع إلى الرقم التالي:",
  dragDropUploadTransaction: "اسحب وأفلت أو انقر لتحميل صورة التحويل",
  cashHandlingFeeMessage:
    "الدفع عند الاستلام يتضمن رسوم مناولة نقدية إضافية بقيمة",
  payLaterMessage:
    "لقد اخترت الدفع لاحقاً. ستدفع ثمن طلبك في وقت لاحق كما تم الاتفاق عليه.",
  back: "رجوع",
  shippingMethod: "طريقة الشحن",
  estimatedDelivery: "وقت التسليم المتوقع:",
  hours: "ساعات",
  fees: "الرسوم:",
  productsTotal: "إجمالي المنتجات",
  coupon: "الكوبون",
  location: "الموقع",
  useCouponCode: "استخدم رمز الكوبون لكسب النقاط",
  enterCoupon: "أدخل الكوبون",
  apply: "تطبيق",
  placeOrder: "تأكيد الطلب",
  selectShippingError: "يرجى اختيار عنوان الشحن وطريقة الشحن وطريقة الدفع.",
  orderPlacedSuccessfully: "تم تقديم الطلب بنجاح!",
  orderPlacedThankYou: "تم تقديم طلبك. شكرا لتسوقك معنا!",
  showOrder: "عرض الطلب",
  keepShopping: "متابعة التسوق",
  changeProfilePicture: "تغيير صورة الملف الشخصي",
  pleaseSelectValidImage: "يرجى اختيار صورة صالحة",
  imageSizeMustBeLess: "حجم الصورة يجب أن يكون أقل من 5 ميجابايت",
  profileImageUpdatedSuccessfully: "تم تحديث صورة الملف الشخصي بنجاح",
  failedToUpdateProfileImage: "فشل تحديث صورة الملف الشخصي",
  errorOccurredWhileUpdatingImage: "حدث خطأ أثناء تحديث الصورة",
  profileUpdatedSuccessfully: "تم تحديث الملف الشخصي بنجاح",
  changesSavedSuccessfully: "تم حفظ التغييرات بنجاح.",
  failedToUpdateProfile: "فشل تحديث الملف الشخصي",
  errorOccurredWhileUpdatingProfile: "حدث خطأ أثناء تحديث الملف الشخصي.",
  viewCertificate: "عرض الشهادة",

  searchByProductOrOrderId: "البحث باسم المنتج أو رقم الطلب",
  pending: "قيد الانتظار",
  confirmed: "مؤكد",
  shipped: "تم الشحن",
  delivered: "تم التوصيل",
  cancelled: "ملغى",
  canceled: "ملغى",
  returned: "مرتجع",
  completed: "مكتمل",

  cancelOrder: "إلغاء الطلب",
  cancelling: "جاري الإلغاء...",
  cancelOrderConfirmTitle: "هل أنت متأكد أنك تريد إلغاء هذا الطلب؟",
  cancelOrderConfirmDescription:
    "لا يمكن التراجع عن هذا الإجراء. يرجى تأكيد قرارك.",
  no: "لا",
  yes: "نعم",
  orderCancelledSuccessfully: "تم إلغاء الطلب بنجاح",
  failedToCancelOrder: "فشل في إلغاء الطلب",
  order: "طلب",
  returnRequested: "طلب إرجاع",
  actions: "الإجراءات",
  removeFromReturn: "إزالة من الإرجاع",
  addToReturn: "إضافة للإرجاع",
  productAddedToRefund: "تمت الإضافة. يمكنك إضافة المزيد أو عرض الطلب.",
  viewRequest: "عرض الطلب",
  returnRequestSubmitted: "تم تقديم طلب الإرجاع",
  returnRequestAlreadySubmitted:
    "تم تقديم طلب إرجاع لهذا الطلب بالفعل. يمكنك عرض الحالة في",
  refundRequests: "طلبات الاسترداد",
  viewReturnRequest: "عرض طلب الإرجاع",
  showReturnRequest: "عرض طلب الإرجاع",
  item: "عنصر",
  items: "عناصر",

  shippingAddress: "عنوان الشحن",
  noShippingAddress: "لم يتم تقديم عنوان الشحن",

  noPaymentMethod: "لم يتم تقديم طريقة الدفع",
  deliveryDate: "تاريخ التسليم",

  noDeliveryDate: "لم يتم تقديم تاريخ التسليم",
  addRating: "أضف تقييم",
  rate: "تقييم",
  pleaseSelectRating: "يرجى اختيار تقييم",
  pleaseAddComment: "يرجى إضافة تعليق",
  addComment: "أضف تعليق",
  submitRating: "إرسال التقييم",
  thankYouForFeedback: "شكرا لك على ملاحظاتك!",
  failedToSubmitFeedback: "فشل في إرسال الملاحظات. يرجى المحاولة مرة أخرى.",
  refundRequest: "طلب استرداد",
  itemsToRefund: "العناصر المراد استردادها",
  noItemsSelected: "لم يتم اختيار عناصر",
  addItemsToRequestRefund: "أضف عناصر من طلبك لطلب الاسترداد",
  purchased: "تم الشراء:",
  quantityToReturn: "الكمية المراد إرجاعها",

  proofImageOptional: "صورة إثبات (اختياري)",
  uploadImage: "رفع صورة",
  remove: "إزالة",
  refundReason: "سبب الاسترداد",
  whyRequestingRefund: "لماذا تطلب استرداد لـ",
  refundSummary: "ملخص الاسترداد",

  estimatedRefund: "الاسترداد المقدر",

  submitRefundRequest: "إرسال طلب الاسترداد",
  refundRequestSubmittedSuccessfully: "تم إرسال طلب الاسترداد بنجاح.",
  failedToSubmitRefundRequest: "فشل في إرسال طلب الاسترداد.",
  priceRange: "نطاق السعر",
  from: "من",
  to: "إلى",
  min: "الحد الأدنى",
  max: "الحد الأقصى",
  customerRating: "تقييم العملاء",
  doctorRating: "تقييم الأطباء",

  searchCategories: "البحث عن الفئات...",

  searchBrands: "البحث عن العلامات التجارية...",
  applyFilters: "تطبيق الفلاتر",
  resetFilters: "إعادة تعيين الفلاتر",
  filters: "الفلاتر",

  loadingNotifications: "جاري تحميل الإشعارات...",
  allNotificationsRead: "جميع الإشعارات مقروءة",
  noNotifications: "لا توجد إشعارات",
  allOrderAndReturnNotifications:
    "ستظهر هنا جميع إشعاراتك المتعلقة بالطلبات والإرجاعات",
  unreadNotifications: "إشعار غير مقروء",
  markAllAsRead: "تعيين الكل كمقروء",
  markAsRead: "تعيين كمقروء",
  notificationMarkedAsRead: "تم تعيين الإشعار كمقروء",
  failedToMarkNotificationAsRead: "فشل في تعيين الإشعار كمقروء",
  allNotificationsMarkedAsRead: "تم تعيين جميع الإشعارات كمقروءة",
  failedToMarkAllNotificationsAsRead: "فشل في تعيين جميع الإشعارات كمقروءة",
  notificationsKeptFor30Days: "سيتم الاحتفاظ بالإشعارات لمدة 30 يوماً",
  now: "الآن",
  since: "منذ",
  hoursAgo: "ساعة",
  daysAgo: "يوم",
  newBadge: "جديد",
  confirmedBadge: "مؤكد",
  shippedBadge: "مُرسل",
  deliveredBadge: "مُسلم",
  canceledBadge: "ملغي",
  returnRequestBadge: "طلب إرجاع",
  acceptedBadge: "مقبول",
  rejectedBadge: "مرفوض",
  notificationBadge: "إشعار",
  failedToLoadNotifications: "فشل في تحميل الإشعارات",
  pleaseLoginToViewFavorites: "الرجاء تسجيل الدخول لعرض المفضلات.",
  logIn: "تسجيل الدخول",
  yourFavoritesList: "مفضلاتك",
  yourFavoritesListIsEmpty: "قائمة المفضلات فارغة.",
  somethingWentWrong: "حدث خطأ ما",
  noFavoriteProductsFound: "لا توجد منتجات مفضلة",
  addedToFavorites: "تمت الإضافة إلى المفضلات",
  removedFromFavorites: "تمت الإزالة من المفضلات",
  needLoginToManageFavorites: "تحتاج إلى تسجيل الدخول لإدارة المفضلات",

  errorLoadingRefundRequests: "خطأ في تحميل طلبات الاسترداد",

  trackAndManageRefundRequests: "تتبع وإدارة طلبات الاسترداد الخاصة بك",
  noRefundRequests: "لا توجد طلبات استرداد",
  noRefundRequestsSubmitted: "لم تقم بتقديم أي طلبات استرداد بعد",
  viewOrders: "عرض الطلبات",
  request: "طلب",

  refundMethod: "طريقة الاسترداد",
  reason: "السبب",

  platformReceived: "تم الاستلام من المنصة",
  pharmacyPending: "في انتظار المتجر",
  pharmacyReceived: "تم الاستلام من المتجر",
  approved: "موافق عليه",
  rejected: "مرفوض",
  refunded: "تم الاسترداد",
  backToRefundRequests: "العودة إلى طلبات الاسترداد",
  returnReason: "سبب الإرجاع",
  platformNotes: "ملاحظات المنصة",
  pharmacyNotes: "ملاحظات المتجر",
  returnedItems: "العناصر المرتجعة",
  product: "المنتج",
  image: "الصورة",
  quantityReturned: "الكمية المرتجعة",
  originalQty: "الكمية الأصلية",
  productId: "معرف المنتج",
  itemNumber: "عنصر",
  original: "الأصلي",
  originalMethod: "الطريقة الأصلية",
  failedToLoadWalletDetails: "فشل في تحميل تفاصيل المحفظة.",
  yourWallet: "محفظتك",
  currentBalance: "الرصيد الحالي",
  availablePoints: "النقاط المتاحة",
  totalPoints: "النقاط المتوفرة",
  transactionHistory: "سجل المعاملات",
  points: "نقطة",
  noTransactionsYet: "لا توجد معاملات بعد.",
  exchangePoints: "تحويل النقاط",
  convertPointsToWallet: "تحويل النقاط إلى المحفظة",
  convertAvailablePointsToWalletBalance:
    "قم بتحويل نقاطك المتاحة إلى رصيد المحفظة. النقاط المتاحة:",
  pointsToConvert: "النقاط المراد تحويلها",
  enterNumberOfPoints: "أدخل عدد النقاط",
  convert: "تحويل",
  pleaseEnterValidNumberOfPoints: "الرجاء إدخال عدد صحيح من النقاط",
  notEnoughPoints: "ليس لديك نقاط كافية",
  pointsConvertedSuccessfully: "تم تحويل النقاط بنجاح!",
  failedToConvertPoints: "فشل تحويل النقاط",
  errorConvertingPoints: "حدث خطأ أثناء تحويل النقاط",
  productComparison: "مقارنة المنتجات",
  noProductsToCompare:
    "لا توجد منتجات للمقارنة. يرجى إضافة منتجات إلى قائمة المقارنة.",
  scientificName: "الاسم العلمي",
  vendor: "المتجر",
  availableQuantity: "الكمية المتاحة",

  expiryDate: "تاريخ الانتهاء",
  userRating: "تقييم المستخدمين",
  pharmacistRating: "تقييم الصيادلة",
  totalAnnualSales: "إجمالي المبيعات السنوية",
  activeVendors: "البائعون النشطون على موقعنا",
  monthlyProductSales: "مبيعات المنتجات الشهرية",
  activeVisitors: "الزائرون النشطون على موقعنا",
  aboutUs: "من نحن",
  weCareAboutYourHealth: "نعتني بصحتك... لأنك تستحق الأفضل",
  weTakeCareToProvide:
    "نحرص على تقديم خدمات دوائية وصحية موثوقة، مدعومة بخبرة فريقنا من الصيادلة المؤهلين الذين يعملون بكل تفاني لتوفير الرعاية التي تستحقها.",
  prescriptionAndOTC: "صرف الأدوية بوصفة طبية وبدون وصفة",
  freePharmacyConsultations: "استشارات صيدلانية مجانية",
  bloodPressureAndSugarMeasurement: "قياس الضغط والسكر",
  babySuppliesAndPersonalCare: "توفير مستلزمات الأطفال والعناية الشخصية",
  specialOffersOnVitamins: "عروض خاصة على الفيتامينات والمكملات الغذائية",
  callUs: "اتصل بنا",
  availableAllWeek: "نحن متواجدون على مدار الساعة طوال أيام الأسبوع.",
  writeToUs: "اكتب لنا",
  fillFormAndGetReply: "املأ استمارتنا وسنتواصل معك خلال 24 ساعة.",
  yourName: "اسمك *",
  yourEmail: "بريدك الإلكتروني *",
  yourPhone: "هاتفك *",
  yourMessage: "رسالتك *",
  sendMessage: "إرسال رسالة",
  sending: "جارٍ الإرسال...",
  messageSentSuccess: "تم إرسال رسالتك بنجاح",
  messageFailedToSend: "فشل إرسال الرسالة",
  errorSendingMessage: "حدث خطأ أثناء إرسال الرسالة",
  fullInventoryManagement: "إدارة كاملة للمخزون",
  basicAnalyticsDashboard: "لوحة تحليلات أساسية",
  emailSupport: "دعم عبر البريد الإلكتروني",
  mobileAppAccess: "الوصول إلى تطبيق الجوال",
  upTo1000Products: "حتى 1000 منتج",
  advancedAnalyticsReports: "تحليلات وتقارير متقدمة",
  priority247Support: "دعم ذو أولوية على مدار الساعة",
  unlimitedProducts: "منتجات غير محدودة",
  customBranding: "علامة تجارية مخصصة",
  apiAccess: "الوصول إلى API",
  dedicatedAccountManager: "مدير حساب مخصص",
  standardAnalyticsDashboard: "لوحة تحليلات قياسية",
  emailChatSupport: "دعم عبر البريد الإلكتروني والدردشة",
  upTo5000Products: "حتى 5000 منتج",
  chooseYourPlan: "اختر خطتك",
  selectPerfectPlanDescription:
    "اختر الخطة المثالية لصيدليتك. تشمل جميع الخطط الميزات الأساسية مع أسعار مرنة تناسب احتياجاتك.",
  failedToLoadPlans: "فشل تحميل الخطط",
  failedToLoadPlansShowingDefault: "فشل تحميل الخطط. عرض الخطط الافتراضية.",
  mostPopular: "الأكثر شعبية",
  monthly: "شهري",
  perMonth: "شهر",
  days: "يوم",
  subscribeNow: "اشترك الآن",
  needHelpChoosingPlan: "هل تحتاج مساعدة في اختيار خطة؟",
  contactSalesDescription:
    "اتصل بفريق المبيعات للحصول على توصيات مخصصة وحلول مؤسسية مخصصة.",
  contactSales: "اتصل بالمبيعات",
  subscribeTo: "الاشتراك في",
  plan: "خطة",
  fillDetailsToSubscribe: "املأ بياناتك لإكمال اشتراكك",
  personalInformation: "المعلومات الشخصية",
  fullName: "الاسم الكامل",
  minCharacters: "8 أحرف على الأقل",
  reEnterPassword: "أعد إدخال كلمة المرور",
  pharmacyInformation: "معلومات المتجر",
  pharmacyNameArabic: "اسم المتجر (عربي)",
  pharmacyNameEnglish: "اسم المتجر (إنجليزي)",
  addressArabic: "العنوان (عربي)",
  addressEnglish: "العنوان (إنجليزي)",
  pharmacyPhone: "هاتف المتجر",
  pharmacyEmail: "بريد المتجر الإلكتروني",
  selectPaymentMethod: "اختر طريقة الدفع",
  creditDebitCard: "بطاقة ائتمان/خصم",
  digitalWallet: "محفظة رقمية",
  processing: "جارٍ المعالجة...",
  subscriptionSuccessful: "تم الاشتراك بنجاح! مرحباً بك! 🎉",
  failedToSubscribe: "فشل الاشتراك. يرجى المحاولة مرة أخرى.",
  privacyPolicyDescription: "سياسة الخصوصية وحماية البيانات الشخصية",
  termsOfServiceDescription: "شروط وأحكام استخدام منصة Valideria",
  failedToLoadPrivacyPolicy: "فشل تحميل سياسة الخصوصية",
  failedToLoadTermsOfService: "فشل تحميل شروط الاستخدام",
  openNow: "مفتوح الآن",
  closed: "مغلق",
  store: "المتجر",
  certificateImage: "صورة الشهادة",

  // FAQ Page (custom additions)

  faqTitle: "الأسئلة الشائعة",
  faqDescription:
    "هل لديك أسئلة؟ تحقق من الأسئلة الشائعة أدناه للحصول على إجابات سريعة حول خدماتنا، الطلبات، الشحن، وأكثر من ذلك.",
  noFaqsForNow: " لا توجد أسئلة شائعة حالياً.",
  didntFindAnswer: "لم تجد إجابتك؟",
  contactUsForMoreHelp: "اتصل بنا لمزيد من المساعدة.",

  // Comments Report Page (custom additions)
  errorLoadingReport: "حدث خطأ أثناء تحميل التقرير",
  noDataAvailable: "لا توجد بيانات متاحة",
  doctorName: "اسم الطبيب",
  totalComments: "إجمالي التعليقات",

  topPharmacy: "أفضل صيدلية",

  applyFilter: "تطبيق الفلتر",

  comment: "التعليق",
  addedAt: "تاريخ الإضافة",
  updatedAt: "آخر تحديث",

  // Reviews Report Page (custom additions)

  promoCodeUsage: "استخدام الكود",
  doctorOrders: "طلبات الطبيب",
  doctorOrdersCount: "عدد الطلبات من الطبيب",
  patientOrders: "طلبات المرضى",
  patientOrdersCount: "عدد طلبات المرضى",
  pointsFromPatients: "نقاط من المرضى",
  pointsEarnedFromPatients: "النقاط المكتسبة من المرضى",
  pharmacyPoints: "نقاط الصيدلية",
  sitePoints: "نقاط الموقع",
  customerName: "اسم العميل",
  ordersCount: "عدد الطلبات",
  date: "التاريخ",
  source: "المصدر",

  // forget password
  forgetPassword: "نسيت كلمة المرور؟",
  forgetPasswordTitle: "استعادة كلمة المرور",
  forgetPasswordDescription:
    "أدخل عنوان بريدك الإلكتروني لتلقي رابط لإعادة تعيين كلمة المرور الخاصة بك.",
  emailAddress: "عنوان البريد الإلكتروني",
  enterYourEmail: "أدخل بريدك الإلكتروني",
  resetPassword: "إعادة تعيين كلمة المرور",
  resetPasswordDescription:
    "أدخل رمز التحقق المرسل إلى بريدك الإلكتروني وقم بتعيين كلمة مرور جديدة لحسابك.",
  sendResetLink: "إرسال رابط إعادة التعيين",
  resetLinkSent: "تم إرسال رابط إعادة التعيين إلى بريدك الإلكتروني",
  tokenRequired: "مطلوب رمز التحقق لإعادة تعيين كلمة المرور",
  verifyEmailButton: "تحقق",
  emailNotFound: "البريد الإلكتروني غير موجود",
  checkYourEmailForSecretKey: "تحقق من بريدك الإلكتروني للحصول على رمز التحقق.",
  secretKey: "رمز التحقق",
  newpassword: "كلمة المرور الجديدة",
  confirmNewPassword: "تأكيد كلمة المرور الجديدة",
  passwordResetSuccess:
    "تم إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.",
};

export default ar;
