const en = {
  // General
  welcome: "Welcome",
  cart: "Cart",
  viewCart: "View Cart",
  total: "Total",
  elements: "elements",
  currentLang: "En",
  currentLanguage: "English",
  offers: "Offers",
  doctorPrefix: "Dr.",

  // Accessibility
  menu: "Menu",
  toggleTheme: "Toggle theme",
  switchLanguage: "Switch language",
  shareProduct: "Share product",
  openCart: "Open cart",
  firstPage: "First page",
  previousPage: "Previous page",
  nextPage: "Next page",
  lastPage: "Last page",
  goToPage: "Go to page",
  removeFromFavorites: "Remove from favorites",
  addToFavorites: "Add to favorites",

  // Navigation
  home: "Home",
  about: "About",
  contactUs: "Contact Us",
  products: "Products",
  categories: "Categories",
  brands: "Brands",

  // Search
  allCategories: "All Categories",
  searchForProducts: "Search for products...",
  noResultsFound: "No results found",

  // Account
  account: "Account",
  signin: "Signin",
  signup: "Signup",
  signOut: "Sign Out",
  notification: "Notification",
  personalInfo: "Personal Info",
  addresses: "Addresses",
  returns: "Returns",
  wallet: "Wallet",
  compareProducts: "Compare Products",
  favorites: "Favorites",
  orders: "Orders",
  notifications: "Notifications",
  reports: "Reports",
  logout: "Logout",

  // Profile
  firstName: "First Name",
  lastName: "Last Name",
  phone: "Phone Number",
  email: "Email",
  age: "Age",
  gender: "Gender",
  address: "Address",
  specialization: "Specialization",
  licenseNumber: "License Number",
  bio: "Professional Bio",
  certificate: "Certificate File",
  promoCode: "Promo Code",
  accountDetails: "Account Details",
  selectSpecialization: "Select specialization",
  professionalInfo: "Professional Information",
  save: "Save",
  saveChanges: "Save Changes",
  cancel: "Cancel",

  // Orders
  orderNumber: "Order Number",
  orderStatus: "Order Status",
  orderDate: "Order Date",
  orderTotal: "Order Total",
  viewDetails: "View Details",
  requestReturn: "Request Return",

  // Products
  productName: "Product Name",
  quantity: "Quantity",
  buyNow: "Buy Now",
  description: "Description",
  reviews: "Reviews",
  specifications: "Specifications",

  // Cart & Checkout
  cartEmpty: "Your cart is empty",
  continueShopping: "Continue Shopping",
  shipping: "Shipping",
  tax: "Tax",
  discount: "Discount",
  login: "Login",
  loginToViewCart: "to view your cart",
  pharmacies: "Pharmacies",
  youHaveOrdersWith: "You have orders with",

  // Payment
  paymentMethod: "Payment Method",
  card: "Card",
  cashOnDelivery: "Cash on Delivery",
  payLater: "Pay Later",

  // Auth
  signInTitle: "Sign In",
  signInDescription: "Sign in to your account",
  signUpTitle: "Sign Up",
  signUpDescription: "Create your account, enter your information below.",
  selectUserType: "Select User Type",
  user: "User",
  doctor: "Doctor",
  dontHaveAccount: "Don't have an account?",
  alreadyHaveAccount: "Already have an account?",
  password: "Password",
  confirmPassword: "Confirm Password",
  invalidEmailOrPassword: "Invalid email or password",
  male: "Male",
  female: "Female",
  register: "Register",
  confirmLogout: "Confirm Logout",
  confirmLogoutMessage: "Are you sure you want to log out?",
  yesLogout: "Yes, Logout",
  lightMode: "Light Mode",
  darkMode: "Dark Mode",
  myOrders: "My Orders",
  myChats: "Chats",
  myDose: "My Dose",

  // Forms
  submit: "Submit",
  clear: "Clear",
  search: "Search",
  filter: "Filter",
  reset: "Reset",

  // Validation Errors
  firstNameRequired: "First name is required",
  lastNameRequired: "Last name is required",
  addressRequired: "Address is required",
  genderMustBeMaleOrFemale: "Gender must be either 'male' or 'female'",
  ageRequired: "Age must be a valid number",
  phoneNumberMin: "Phone number must be at least 5 characters",
  phoneNumberMax: "Phone number must not exceed 20 characters",
  invalidPhoneNumber:
    "Invalid phone number. Only digits, +, -, _, (), spaces, and . are allowed.",
  phoneNumberMustHaveDigit: "Phone number must contain at least one digit",
  emailRequired: "Email must be a valid email address",
  passwordMin: "Password must be at least 8 characters",
  passwordConfirmationMin:
    "Password confirmation must be at least 8 characters",
  passwordsMustMatch: "Passwords must match",
  licenseNumberRequired: "License number is required",
  specializationRequired: "Specialization is required",
  certificateFileInvalid:
    "Certificate file must be a valid PDF, DOC, DOCX, JPG, PNG, JPEG, or SVG file URL",
  invalidCurrencyFormat: "Invalid currency format",
  productIdRequired: "Product ID is required",
  productNameRequired: "Product name is required",
  productSlugRequired: "Product slug is required",
  quantityMin: "Quantity must be at least 1",
  imageMustBeUrl: "Image must be a valid URL",
  cartMinItems: "Cart must have at least one item",
  totalItemsMin: "Total items must be at least 1",
  discountMin: "Discount must be at least 0",
  sessionCartIdRequired: "Session Cart ID is required",
  nameRequired: "Name is required",
  cardNumberInvalid: "Card number must be 16 digits",
  expiryInvalid: "Expiry must be in MM/YY format",
  cvvInvalid: "Invalid CVV",
  firstNameMin: "First name must be at least 2 characters",
  ageMin: "Age must be a valid number",
  profileImageUrl: "Profile image must be a valid URL",
  addressNameRequired: "Address name is required",
  buildingRequired: "Building is required",
  areaRequired: "Area is required",
  cityRequired: "City is required",
  planIdRequired: "Plan ID is required",
  pharmacyNameArRequired: "Pharmacy name in Arabic is required",
  pharmacyNameEnRequired: "Pharmacy name in English is required",
  pharmacyAddressArRequired: "Pharmacy address in Arabic is required",
  pharmacyAddressEnRequired: "Pharmacy address in English is required",
  pharmacyEmailInvalid: "Pharmacy email must be a valid email address",
  paymentMethodInvalid:
    "Payment method must be either 'card', 'cash', or 'wallet'",
  currentPasswordRequired: "Current password is required",
  newPasswordMin: "New password must be at least 8 characters",
  newPasswordConfirmationMin:
    "New password confirmation must be at least 8 characters",
  newPasswordsMustMatch: "New passwords must match",
  messageRequired: "Message is required",

  // Messages
  success: "Success",
  error: "Error",
  loading: "Loading...",
  noData: "No data available",
  confirmDelete: "Are you sure you want to delete?",

  // Common Actions
  edit: "Edit",
  view: "View",
  download: "Download",
  upload: "Upload",
  close: "Close",
  previous: "Previous",

  // Reports
  comments: "Comments",
  reviewsReport: "Reviews Report",
  commentsReport: "Comments Report",
  promocodes: "Promocodes",

  // Misc
  showMore: "Show More",
  showLess: "Show Less",
  browseAll: "Browse all",
  uniqueProducts: "Unique Products",
  topRatedProducts: "Top Rated Products",
  topSellingProducts: "Top Selling Products",
  top: "Top",
  ratedBrands: "Rated Brands",
  categoriesSubheading:
    "Choose from a wide range of medicines, health products, and personal care products – everything you need in one place.",
  brandsSubheading:
    "Choose from a wide range of medicines, health products, and personal care products – everything you need in one place.",
  viewAll: "View All",
  availableInStock: "Available in Stock",
  notAvailable: "Not Available",
  buyNowButton: "Buy Now",
  details: "Details",
  compare: "Compare",
  support: "Support",
  quickLink: "Quick Link",
  downloadApp: "Download App",
  allRightsReserved: "All rights reserved",
  signInRegister: "Sign In / Register",
  wishlist: "Wishlist",
  privacyPolicy: "Privacy Policy",
  termsOfService: "Terms of Service",
  faq: "FAQ",
  addToCompare: "Add to Compare",
  productDetails: "Product Details",
  genericName: "Generic Name",
  category: "Category",
  brand: "Brand",
  productType: "Type",
  form: "Form",
  strength: "Strength",
  productionDate: "Production Date",
  packSize: "Pack Size",
  rateProduct: "Rate Product",
  productNotFound: "Product Not Found",
  productNotFoundDescription:
    "The requested product is not currently available. Browse our wide range of medicines and health products.",
  similarProducts: "Similar Products",
  price: "Price",
  status: "Status",
  inStock: "In Stock",
  outOfStock: "Out Of Stock",
  addToCart: "Add to Cart",
  itemAddedToCart: "Item added to cart successfully",
  itemUpdatedInCart: "Item updated in cart successfully",
  notEnoughStock: "Not enough stock available",
  notSignedIn: "You are not signed in!",
  goToSignIn: "go to sign in",
  doctors: "Doctors",
  customers: "Customers",
  doctorComments: "Doctor Comments",
  customerComments: "Customer Comments",
  noCustomerComments: "No customer comments yet.",
  noDoctorComments: "No doctor comments yet.",
  productReviews: "Product Ratings and Reviews",
  showAll: "Show all",
  shoppingCart: "Shopping Cart",
  manageCartAcrossStores: "Manage your shopping cart across different stores",
  pharmacy: "Pharmacy",
  productsCount: "Products Count",
  totalAmount: "Total",
  pricePerUnit: "Price per unit",
  orderSummary: "Order Summary",
  subtotal: "Subtotal",
  estimatedTax: "Estimated Tax",
  walletBalance: "Wallet Balance",
  checkout: "Checkout",
  noAddressesAvailable: "No addresses available",
  addNewAddress: "Add New Address",
  name: "Name",
  phoneNumber: "Phone Number",
  building: "Building",
  city: "City",
  area: "Area",
  unitPrice: "Unit Price",
  makeDefaultAddress: "Make default address",
  addressSavedSuccessfully: "Address saved successfully",
  failedToSaveAddress: "Failed to save address",
  addressDeletedSuccessfully: "Address deleted successfully",
  defaultAddress: "Default Address",
  deleteAddress: "Delete Address",
  deleteAddressConfirmation: "Are you sure you want to delete this address?",
  delete: "Delete",
  chooseLocation: "Choose Location",
  default: "default",
  next: "Next",
  savedCards: "Saved Cards",
  expired: "Expired",
  transferPaymentToNumber:
    "Please transfer the payment to the following number:",
  dragDropUploadTransaction: "Drag & drop or click to upload transaction image",
  cashHandlingFeeMessage:
    "Cash on Delivery incurs an additional cash handling fee of",
  payLaterMessage:
    "You have chosen Pay Later. You will pay for your order at a later time as agreed.",
  back: "Back",
  shippingMethod: "Shipping Method",
  estimatedDelivery: "Estimated delivery:",
  hours: "hours",
  fees: "Fees:",
  productsTotal: "Products Total",
  coupon: "Coupon",
  location: "Location",
  useCouponCode: "use coupon code to earn points",
  enterCoupon: "Enter Coupon",
  apply: "Apply",
  placeOrder: "Place Order",
  selectShippingError:
    "Please select a shipping address, shipping method, and payment method.",
  orderPlacedSuccessfully: "Order Placed Successfully!",
  orderPlacedThankYou:
    "Your order has been placed. Thank you for shopping with us!",
  showOrder: "Show Order",
  keepShopping: "Keep Shopping",
  changeProfilePicture: "Change profile picture",
  pleaseSelectValidImage: "Please select a valid image",
  imageSizeMustBeLess: "Image size must be less than 5MB",
  profileImageUpdatedSuccessfully: "Profile image updated successfully",
  failedToUpdateProfileImage: "Failed to update profile image",
  errorOccurredWhileUpdatingImage: "An error occurred while updating the image",
  profileUpdatedSuccessfully: "Profile updated successfully",
  changesSavedSuccessfully: "Changes saved successfully.",
  failedToUpdateProfile: "Failed to update profile",
  errorOccurredWhileUpdatingProfile:
    "An error occurred while updating the profile.",
  viewCertificate: "View Certificate",
  searchByProductOrOrderId: "Search by product name or order ID",
  pending: "Pending",
  confirmed: "Confirmed",
  shipped: "Shipped",
  delivered: "Delivered",
  cancelled: "Cancelled",
  canceled: "Canceled",
  returned: "Returned",
  completed: "Completed",
  cancelOrder: "Cancel Order",
  cancelling: "Cancelling...",
  cancelOrderConfirmTitle: "Are you sure you want to cancel this order?",
  cancelOrderConfirmDescription:
    "This action cannot be undone. Please confirm your decision.",
  no: "No",
  yes: "Yes",
  orderCancelledSuccessfully: "Order canceled successfully",
  failedToCancelOrder: "Failed to cancel order",
  order: "Order",
  returnRequested: "Return Requested",
  actions: "Actions",
  removeFromReturn: "remove from return",
  addToReturn: "Add to Return",
  productAddedToRefund: "has been added. You can add more or view the request.",
  viewRequest: "View Request",
  returnRequestSubmitted: "Return Request Submitted",
  returnRequestAlreadySubmitted:
    "A return request has already been submitted for this order. You can view the status in your",
  refundRequests: "refund requests",
  viewReturnRequest: "View Return Request",
  showReturnRequest: "Show Return Request",
  item: "item",
  items: "items",
  shippingAddress: "Shipping Address",
  noShippingAddress: "No shipping address provided",
  noPaymentMethod: "No payment method provided",
  deliveryDate: "Delivery Date",
  noDeliveryDate: "No delivery date provided",
  addRating: "Add Rating",
  rate: "Rate",
  pleaseSelectRating: "Please select a rating",
  pleaseAddComment: "Please add a comment",
  addComment: "Add a comment",
  submitRating: "Submit Rating",
  thankYouForFeedback: "Thank you for your feedback!",
  failedToSubmitFeedback: "Failed to submit feedback. Please try again.",
  refundRequest: "Refund Request",
  itemsToRefund: "Items to Refund",
  noItemsSelected: "No items selected",
  addItemsToRequestRefund: "Add items from your order to request a refund",
  purchased: "Purchased:",
  quantityToReturn: "Quantity to Return",
  proofImageOptional: "Proof Image (Optional)",
  uploadImage: "Upload image",
  remove: "Remove",
  refundReason: "Refund Reason",
  whyRequestingRefund: "Why are you requesting a refund for",
  refundSummary: "Refund Summary",
  estimatedRefund: "Estimated Refund",
  submitRefundRequest: "Submit Refund Request",
  refundRequestSubmittedSuccessfully: "Refund request submitted successfully.",
  failedToSubmitRefundRequest: "Failed to submit refund request.",
  priceRange: "Price Range",
  from: "From",
  to: "To",
  min: "Min",
  max: "Max",
  customerRating: "Customer Rating",
  doctorRating: "Doctor Rating",
  searchCategories: "Search categories...",
  searchBrands: "Search brands...",
  applyFilters: "Apply Filters",
  resetFilters: "Reset Filters",
  filters: "Filters",
  loadingNotifications: "Loading notifications...",
  allNotificationsRead: "All notifications read",
  noNotifications: "No notifications",
  allOrderAndReturnNotifications:
    "All your order and return notifications will appear here",
  unreadNotifications: "unread notifications",
  markAllAsRead: "Mark all as read",
  markAsRead: "Mark as read",
  notificationMarkedAsRead: "Notification marked as read",
  failedToMarkNotificationAsRead: "Failed to mark notification as read",
  allNotificationsMarkedAsRead: "All notifications marked as read",
  failedToMarkAllNotificationsAsRead:
    "Failed to mark all notifications as read",
  notificationsKeptFor30Days: "Notifications will be kept for 30 days",
  now: "Now",
  since: "since",
  hoursAgo: "hours ago",
  daysAgo: "days ago",
  newBadge: "New",
  confirmedBadge: "Confirmed",
  shippedBadge: "Shipped",
  deliveredBadge: "Delivered",
  canceledBadge: "Canceled",
  returnRequestBadge: "Return Request",
  acceptedBadge: "Accepted",
  rejectedBadge: "Rejected",
  notificationBadge: "Notification",
  failedToLoadNotifications: "Failed to load notifications",
  pleaseLoginToViewFavorites: "Please log in to view your favorites.",
  logIn: "Log in",
  yourFavoritesList: "Your Favorites",
  yourFavoritesListIsEmpty: "Your favorites list is empty.",
  somethingWentWrong: "Something went wrong",
  noFavoriteProductsFound: "No favorite products found",
  addedToFavorites: "Added to favorites",
  removedFromFavorites: "Removed from favorites",
  needLoginToManageFavorites: "You need to log in to manage favorites",
  errorLoadingRefundRequests: "Error Loading Refund Requests",
  trackAndManageRefundRequests: "Track and manage your refund requests",
  noRefundRequests: "No Refund Requests",
  noRefundRequestsSubmitted: "You haven't submitted any refund requests yet",
  viewOrders: "View Orders",
  request: "Request",
  refundMethod: "Refund Method",
  reason: "Reason",
  platformReceived: "Platform Received",
  pharmacyPending: "Pharmacy Pending",
  pharmacyReceived: "Pharmacy Received",
  approved: "Approved",
  rejected: "Rejected",
  refunded: "Refunded",
  backToRefundRequests: "Back to Refund Requests",
  returnReason: "Return Reason",
  platformNotes: "Platform Notes",
  pharmacyNotes: "Pharmacy Notes",
  returnedItems: "Returned Items",
  product: "Product",
  image: "Image",
  quantityReturned: "Quantity Returned",
  originalQty: "Original Qty",
  productId: "Product ID",
  itemNumber: "Item",
  original: "Original",
  originalMethod: "Original Method",
  failedToLoadWalletDetails: "Failed to load wallet details.",
  yourWallet: "Your Wallet",
  currentBalance: "Current Balance",
  availablePoints: "Available Points",
  totalPoints: "Total Points",
  transactionHistory: "Transaction History",
  points: "points",
  noTransactionsYet: "No transactions yet.",
  exchangePoints: "Exchange Points",
  convertPointsToWallet: "Convert Points to Wallet",
  convertAvailablePointsToWalletBalance:
    "Convert your available points to wallet balance. Available points:",
  pointsToConvert: "Points to Convert",
  enterNumberOfPoints: "Enter number of points",
  convert: "Convert",
  pleaseEnterValidNumberOfPoints: "Please enter a valid number of points",
  notEnoughPoints: "You don't have enough points",
  pointsConvertedSuccessfully: "Points converted successfully!",
  failedToConvertPoints: "Failed to convert points",
  errorConvertingPoints: "An error occurred while converting points",
  productComparison: "Product Comparison",
  noProductsToCompare:
    "No products to compare. Please add products to the comparison list.",
  scientificName: "Scientific Name",
  vendor: "Vendor",
  availableQuantity: "Available Quantity",
  expiryDate: "Expiry Date",
  userRating: "User Rating",
  pharmacistRating: "Pharmacist Rating",
  totalAnnualSales: "Total Annual Sales",
  activeVendors: "Active Vendors on Our Site",
  monthlyProductSales: "Monthly Product Sales",
  activeVisitors: "Active Visitors on Our Site",
  aboutUs: "About Us",
  weCareAboutYourHealth:
    "We care about your health... because you deserve the best",
  weTakeCareToProvide:
    "We take care to provide reliable pharmaceutical and healthcare services, backed by the experience of our team of qualified pharmacists who work with dedication to provide the care you deserve.",
  prescriptionAndOTC: "Dispensing prescription and over-the-counter medicines",
  freePharmacyConsultations: "Free pharmacy consultations",
  bloodPressureAndSugarMeasurement: "Blood pressure and sugar measurement",
  babySuppliesAndPersonalCare: "Providing baby supplies and personal care",
  specialOffersOnVitamins: "Special offers on vitamins and dietary supplements",
  callUs: "Call Us",
  availableAllWeek: "We are available 24/7.",
  writeToUs: "Write to Us",
  fillFormAndGetReply:
    "Fill out our form and we will contact you within 24 hours.",
  yourName: "Your Name *",
  yourEmail: "Your Email *",
  yourPhone: "Your Phone *",
  yourMessage: "Your Message *",
  sendMessage: "Send Message",
  sending: "Sending...",
  messageSentSuccess: "Your message has been sent successfully",
  messageFailedToSend: "Failed to send message",
  errorSendingMessage: "An error occurred while sending the message",
  fullInventoryManagement: "Full inventory management",
  basicAnalyticsDashboard: "Basic analytics dashboard",
  emailSupport: "Email support",
  mobileAppAccess: "Mobile app access",
  upTo1000Products: "Up to 1000 products",
  advancedAnalyticsReports: "Advanced analytics & reports",
  priority247Support: "Priority 24/7 support",
  unlimitedProducts: "Unlimited products",
  customBranding: "Custom branding",
  apiAccess: "API access",
  dedicatedAccountManager: "Dedicated account manager",
  standardAnalyticsDashboard: "Standard analytics dashboard",
  emailChatSupport: "Email & chat support",
  upTo5000Products: "Up to 5000 products",
  chooseYourPlan: "Choose Your Plan",
  selectPerfectPlanDescription:
    "Select the perfect plan for your pharmacy. All plans include core features with flexible pricing to match your needs.",
  failedToLoadPlans: "Failed to load plans",
  failedToLoadPlansShowingDefault:
    "Failed to load plans. Showing default plans.",
  mostPopular: "Most Popular",
  monthly: "Monthly",
  perMonth: "month",
  days: "days",
  subscribeNow: "Subscribe Now",
  needHelpChoosingPlan: "Need help choosing a plan?",
  contactSalesDescription:
    "Contact our sales team for personalized recommendations and custom enterprise solutions.",
  contactSales: "Contact Sales",
  subscribeTo: "Subscribe to",
  plan: "Plan",
  fillDetailsToSubscribe: "Fill in your details to complete your subscription",
  personalInformation: "Personal Information",
  fullName: "Full Name",
  minCharacters: "Min. 8 characters",
  reEnterPassword: "Re-enter your password",
  pharmacyInformation: "Pharmacy Information",
  pharmacyNameArabic: "Pharmacy Name (Arabic)",
  pharmacyNameEnglish: "Pharmacy Name (English)",
  addressArabic: "Address (Arabic)",
  addressEnglish: "Address (English)",
  pharmacyPhone: "Pharmacy Phone",
  pharmacyEmail: "Pharmacy Email",
  selectPaymentMethod: "Select payment method",
  creditDebitCard: "Credit/Debit Card",
  digitalWallet: "Digital Wallet",
  processing: "Processing...",
  subscriptionSuccessful: "Subscription successful! Welcome aboard! 🎉",
  failedToSubscribe: "Failed to subscribe. Please try again.",
  privacyPolicyDescription: "Privacy Policy and Personal Data Protection",
  termsOfServiceDescription: "Terms and Conditions of Using Valideria Platform",
  failedToLoadPrivacyPolicy: "Failed to load privacy policy",
  failedToLoadTermsOfService: "Failed to load terms of service",
  refundAmount: "Refund Amount",

  // FAQ Page
  noFaqsForNow: "No FAQs available for now.",
  faqTitle: "Frequently Asked Questions",
  faqDescription:
    "Find answers to common questions about our services and platform.",
  didntFindAnswer: "Didn't find the answer you were looking for?",
  contactUsForMoreHelp: "Contact us for more help.",

  // Comments Report Page (custom additions)
  errorLoadingReport: "An error occurred while loading the report",
  noDataAvailable: "No data available",
  doctorName: "Doctor Name",
  totalComments: "Total Comments",

  topPharmacy: "Top Pharmacy",

  applyFilter: "Apply Filter",

  comment: "Comment",
  addedAt: "Added At",
  updatedAt: "Updated At",

  // Reviews Report Page (custom additions)
  promoCodeUsage: "Promo Code Usage",
  ordersCount: "Orders Count",
  doctorOrders: "Doctor Orders",
  doctorOrdersCount: "Number of orders from doctor",
  patientOrders: "Patient Orders",
  patientOrdersCount: "Number of patient orders",
  pointsFromPatients: "Points from Patients",
  pointsEarnedFromPatients: "Points earned from patients",
  pharmacyPoints: "Pharmacy Points",
  sitePoints: "Site Points",

  customerName: "Customer Name",
  date: "Date",
  source: "Source",
};

export default en;

export type Locale = typeof en;
